### ISSUE TITLE
Page votes + récompenses automatique (Panel) 

### ISSUE THREAD

**Issue by Emilien52** [CraftMyWebsite/CMW#123]
- [ ] Le reset automatique ne marche pas

- [ ] Récompenses automatique au bout de X votes non fonctionnels

- [ ] Bouton pour obliger la connexion au serveur + site se décoche (visuel uniquement)

- [ ] (modification) ajouter une option pour que le message s'envoie automatiquement s'en appuyer sur le bouton récupérer la récompense

**Comment by guedesite** [comment]
done ( mise à pars le dernier, je trouve ça inutile et cela niquerais tous le système de vote)
