### ISSUE TITLE
Caractères des mails non fonctionnels 

### ISSUE THREAD

**Issue by Emilien52** [CraftMyWebsite/CMW#126]
Les caractères sur les mails ne fonctionnent pas 

Pages touchés:
- Bouton "Tester" dans le smtp
- Page vérifications email (+ saut de ligne impossible)
- NewsLetter (à vérifier)

Image:
https://cdn.discordapp.com/attachments/604710918592528384/775477334701506621/Screenshot_20201109-224940_Yahoo_Mail.jpg

**Comment by PinglsDzn** [comment]
Je vais essayé de regardé ce probléme ! Je vous tiens au courant 😀

**Comment by Emilien52** [comment]
des nouvelles ?

**Comment by enzomtpYT** [comment]
Je rajoute juste que les images ne sont envoyées ( en tout cas dans l'email de vérification )

**Comment by Emilien52** [comment]
A été corrigé sur la 1.8.2
