### ISSUE TITLE
Bugs des grades (affichage et administration)

### ISSUE THREAD

**Issue by AliasPedroKarim** [CraftMyWebsite/CMW#129]
Nom fichier : admin/assets/js/membres.php
Screen avant: https://ascencia.is-inside.me/Qh6VlyWP.png
Screen changement :  https://ascencia.is-inside.me/pD740Jx0.png
Description : La variable global "grade" qui est une Map JS n'avait pas les bonnes clés. 
Les clés de la variable `grade` était une simple itération du nombre de grade présent dans la base de donné au lieu que ça soit l'id des grades en base de donnée.
Donc j'ai juste fais en sorte que les clés des grades dans variable `grade` soit l'id des grades en base de donné.
Le problème qui ce posé après c'est que l'utilisateur ce retrouver assigné un id de grade parfois mauvais.

---

Nom fichier : modele/app/membres.class.php
Screen avant : https://ascencia.is-inside.me/8zyvOCSv.png
Screen changement : https://ascencia.is-inside.me/9CxYluvj.png
Description : Ancien système d'affichage de grade.

**Comment by Emilien52** [comment]
Bonjour @AliasPedroKarim  

ça me semble correcte :) 

Je vous invite à pull votre modification dans la branche développement

**Comment by AliasPedroKarim** [comment]
La réparation a été rajouté, je ferme cette issue. Merci, pour votre aide !
