### ISSUE TITLE
Bugs sur les grades (Panel et thème)

### ISSUE THREAD

**Issue by Emilien52** [CraftMyWebsite/CMW#131]
Partie Panel: 
-  L'attribution des permissions par grade ne fonctionnent pas (Le système retient bien les permissions attribué mais le joueur ne peut pourtant pas bénéficier de ces permissions) 

Partie Thème:
-  La visibilité du grade du joueur sur le forum :x: **On voit bien son grade, mais le FOND DE COULEUR ne s'affiche pas 
- Mauvais nom sur la liste des membres (à vérifier) 

PS: Les images sont sur discord

**Comment by guedesite** [comment]
done
