### ISSUE TITLE
Bug panier 

### ISSUE THREAD

**Issue by Emilien52** [CraftMyWebsite/CMW#133]
Quand on fais un achat et qu'on finalise sur le panier on fini sur une page blanche

**Comment by J4thgit** [comment]
Lorsque l'on met **error_reporting(E_ALL)** l'erreur obtenue est:

`Warning: in_array() expects parameter 2 to be array, bool given in /var/www/rymecraft.mtxserv.com/public_html/controleur/boutique/achat.php on line 71

Fatal error: Uncaught xPaw\SourceQuery\Exception\SocketException: You must set a RCON password before trying to execute a RCON command. in /var/www/rymecraft.mtxserv.com/public_html/modele/json/SourceQuery.php:564 Stack trace: #0 /var/www/rymecraft.mtxserv.com/public_html/modele/json/json.class.php(137): xPaw\SourceQuery\SourceQuery->Rcon('say \xC2\xA74Ceci est...') #1 /var/www/rymecraft.mtxserv.com/public_html/controleur/boutique/achat.php(166): JsonCon->SendBroadcast('\xC2\xA74Ceci est un ...') #2 /var/www/rymecraft.mtxserv.com/public_html/controleur/boutique/achat.php(88): SendCommand(Object(JsonCon), '1', '&4Ceci est un t...', '1', Object(PDO), Array) #3 /var/www/rymecraft.mtxserv.com/public_html/controleur/action.php(318): include('/var/www/rymecr...') #4 /var/www/rymecraft.mtxserv.com/public_html/index.php(68): require_once('/var/www/rymecr...') #5 {main} thrown in /var/www/rymecraft.mtxserv.com/public_html/modele/json/SourceQuery.php on line 564`

**Comment by Emilien52** [comment]
Résolu 

(Mauvais mdp rcon)

**Comment by guedesite** [comment]
done ( j'ai amélioré la sécurité à ce niveau )
