### ISSUE TITLE
Historique paypal 

### ISSUE THREAD

**Issue by Emilien52** [CraftMyWebsite/CMW#155]
l'historique paypal sur le panel ne s'affiche pas 

La table prévu pour ça (cmw_paypal_historique) est vide

**Comment by Emilien52** [comment]
Edit du message. 

La table cmw_paypal_historique est vide, aucune info ne si enregistre

**Comment by guedesite** [comment]
J'ai fix depuis un moment il reste plus qu'à tester

**Comment by Emilien52** [comment]
résolu sur la version 1.8.2
