### ISSUE TITLE
à l'inscription:

### ISSUE THREAD

**Issue by Emilien52** [CraftMyWebsite/CMW#179]
- L'inscription à la newsletter est forcer (à désactiver)
- le mail est forcé sur visible (à cacher)

**Comment by Teyir** [comment]
De mon côté tout fonctionne, je laisse voire si d'autres personnes ont le soucis

**Comment by Emilien52** [comment]
J'ai aussi vérifié de mon coté et finalement sur mes sites il n'y a pas le problème 

@guedesite  tu a vu ça quelque pars ?

**Comment by Emilien52** [comment]
Il semble que ça soit OK

Ceci est donc résolu.

**Comment by thomasmrflamme26** [comment]
C'est toujours d'actualité.
Je m'en charge.

**Comment by thomasmrflamme26** [comment]
Fix effectué sur la page inscription.php
