### ISSUE TITLE
Serveur d'authentification Yggdrasil

### ISSUE THREAD

**Issue by Aeris1One** [CraftMyWebsite/CMW#195]
Bonjour, 
Je cherche un moyen d'avoir un serveur Yggdrasil personnalisé, pour le moment je tourne avec une instance de BlessingSkin en plus de CMW, il serait pratique d'avoir un serveur d'authentification directement integré dans CMW pour éviter à mes joueurs d'avoir besoin de deux comptes.

D'aprés ce que j'ai vu (je ne suis pas un grand codeur PHP) ça m'a l'air finalement assez simple, un exemple d'intégration : https://github.com/wdesportes/minecraft.auth.server qui tient en quelques pages PHP et une base de données.

Merci à vous pour CraftMyWebsite et bonne continuation :)

**Comment by Teyir** [comment]
Salut,

tu pourrais nous en dire plus stp ? 
Car c'est la première fois que j'entends parler de ça

**Comment by Aeris1One** [comment]
Le serveur d'authentification Yggdrasil de mojang (authserver.mojang.com) c'est le serveur que le launcher contacte pour récuperer le compte du joueur. Pour les launchers personnalisés, il est possible de le remplacer par un autre serveur pour utiliser son propre système de compte, c'est ce que je fais avec Blessing Skin.

À propos du protocole : https://wiki.vg/Authentication

**Comment by Emilien52** [comment]
Bonjour, 
Avez vous essayer ce script ? 
https://craftmywebsite.fr/forum/index.php?resources/java-cmw-auth-pour-votre-launcher.168/

**Comment by Aeris1One** [comment]
Non, j'avoue que même en ayant cherché les seuls résultats que j'ai eu sont sur le forum de LaunchMyCraft et sans interet.
Le script à l'air vraiment pas mal mais mon launcher est basé sur HeliosLauncher donc en NodeJS/Electron, je ne peux pas l'implémenter :/

Il serait plus pratique d'avoir un serveur utilisant les mêmes endpoints que le serveur de Mojang (un clone) pour qu'il soit plus simple de baser son launcher dessus.

**Comment by Teyir** [comment]
Effectivement ça peux être sympa

On le note, on regarde comment on peut l'implémenter correctement dans le cms

**Comment by guedesite** [comment]
@Emilien52 possible pour la 1.8.2 ?

**Comment by Aeris1One** [comment]
Je me permet de poser la question, vous avez une idée de quand pourrais sortir la 1.8.2 ? Et la suivante ?

**Comment by Emilien52** [comment]
Nous communiquons rarement sur les dates 
Mais une fois la nouvelle version disponible une annonce est immédiatement fait sur notre discord
