### ISSUE TITLE
Code promo

### ISSUE THREAD

**Issue by DevilishDante** [CraftMyWebsite/CMW#21]
Bonjour, il y a un soucis avec les codes promo en effet lorsqu'en créer deux avec le même code mais un nom différent le premier dans la sql est prit sans distinction de catégorie, donc il faudrait pouvoir soit:

- interdire qu'il y ai deux fois le même code promo dans la sql
- ou vérifier et attribuer la réduction selon la catégorie dans un premier temps , puis avec le code dans un deuxième temps,
- il serait intéressant aussi de pouvoir soustraire un article d'un code genre une immunité au code promo

Merci de m'avoir lu :o

**Comment by Florentlife** [comment]
- [ ] Pour le premier point -> clé pirmaire sur la colonne de nom, ça réglera tout les soucis de conflit

- [ ] Pour le dernier point -> Nouvelle table (id, idCode, idArticle) pour les articules immunisés (voir éventuellement immuniser une categorie, dans ce cas rajouter une colonne boolean pour savoir si idArticle correspond à un identifiant d'article ou de categorie). 

Faisable sur la 1.8, c'est assez rapide
