### ISSUE TITLE
La nouvelle option sur le système de vote n'est pas fonctionnel

### ISSUE THREAD

**Issue by Emilien52** [CraftMyWebsite/CMW#255]
La nouvelle option permettant d'envoyer une commande sur le serveur sans que la personne click sur "récupérer mes récompenses" ne fonctionne pas

**Comment by Emilien52** [comment]
J'avais mis ça comment description sur le trello:

"L'option pour envoyer une récompense directement sur le serveur ne fonctionne pas (nouveauté 1.8.2)"

**Comment by Dancuo-Lohan** [comment]
De mon côté cette fonctionnalité ne pose aucun problème.
J'ai comme site de vote : serveur privé , serveurs mc  et  serveurs minecraft,
j'utilise la récompense automatique avec comme récompense une commande serveur.

Je n'ai pas activé le RCON mais le JSON API pour gérer les interactions site/serveur MC.

**Comment by Emilien52** [comment]
En effet il semble que cela soit fonctionnel 
Le problème devais venir uniquement de mon site web.
