### ISSUE TITLE
Signalement et alerte non fonctionnel

### ISSUE THREAD

**Issue by Emilien52** [CraftMyWebsite/CMW#258]
Les signalements et les alertes ne sont plus fonctionnel depuis plusieurs versions ! 

@CapDrake donnera plus d'information ce soir !

**Comment by CapDRAKE** [comment]
Ces deux pages ne fonctionnent pas
Pour les signalements, ça ne les envoie tout simplement pas dans la page des signalements, il me semble même que le bouton pour signaler ne fonctionne pas.
Pour les alertes, on a un chiffre devant la page affichant le nombre d'alerte, mais rien dans la page. Je ne sais pas si le chiffre affiché à côte est bon mais il me semble que oui. Mais on ne voit pas les alertes.
