### ISSUE TITLE
vérification de vote  serveurminecraft.fr non fonctionnel

### ISSUE THREAD

**Issue by Emilien52** [CraftMyWebsite/CMW#265]
Selon le report de @capdrake la vérification du vote par  serveurminecraft.fr n'est pas fonctionnel

**Comment by CapDRAKE** [comment]
Le système de test de l'api partie admin est fonctionnelle, mais le site ne marche en prod sur le site directement.

**Comment by Teyir** [comment]
Ce site n'existe plus
