### ISSUE TITLE
serveur-minecraft-vote.fr => non validation du vote avec le code unique

### ISSUE THREAD

**Issue by CapDRAKE** [CraftMyWebsite/CMW#276]
Le site serveur-minecraft-vote.fr ne semble pas fonctionner. La partie ADMIN signale bien trouver le code unique, mais le vote ne se valide pas sur la partie publique. 

Cdt 
Capdrake

**Comment by Teyir** [comment]
Visiblement ça serais avec leur API car de notre côté c'est 50 / 50
