### ISSUE TITLE
Ajout d'une erreur

### ISSUE THREAD

**Issue by Emilien52** [CraftMyWebsite/CMW#39]
Ajouter une erreur quand on veux aller sur le panel admin sans y être connecté.

Du Style:

404 not found

Vous devez être connecté pour accéder au panel admin

(Remis sur le nouveau GIT)

**Comment by Emilien52** [comment]
@guedesite je pense y a moyen que tu ajoute ça vite fait

**Comment by Teyir** [comment]
Fais
