### ISSUE TITLE
Erreur Php

### ISSUE THREAD

**Issue by Emilien52** [CraftMyWebsite/CMW#80]
Revoir l'ensemble des pages du panel pour les erreurs php et les corriger.

Assigné à @guedesite

**Comment by Emilien52** [comment]
Page vu pour le moment: 

Payement  (dedipass etc)

Miniature 

(Y en a d'autres)

**Comment by guedesite** [comment]
Miniature fix

**Comment by guedesite** [comment]
fix Payement
J'ai rien vue d'autre en survolant seulement
