### ISSUE TITLE
Gestions des réseaux sociaux sur le panel 

### ISSUE THREAD

**Issue by Emilien52** [CraftMyWebsite/CMW#82]
Impossible de supprimer les réseaux sociaux sur le panel (on peu en ajouter mais pas supprimer) 

Assigné à @BadiiiiX

**Comment by guedesite** [comment]
Je prend, badiix mettra 10 fois plus de temps que moi vue que c'est min code qu'il a utilisé

**Comment by BadiiiiX** [comment]
Fixé avec Guedesite, merci à lui.
