### ISSUE TITLE
I need promo code 

### ISSUE THREAD

**Issue by kevinharry** [CraftMyWebsite/CMW#97]

**Comment by Emilien52** [comment]
Hello 

What ?

**Comment by kevinharry** [comment]
Pls I need promo  code that work

**Comment by kevinharry** [comment]
I also  need bank loging

**Comment by guedesite** [comment]
Useless.

**Comment by kevinharry** [comment]
I need to learn  how to type here

**Comment by Emilien52** [comment]
Hello,

We are a French community working on a minecraft cms.

What can we do for you?

^Emilien52

**Comment by kevinharry** [comment]
I need promo code
